config/routes.rb
Rails.application.routes.draw do
  get 'candidatures/apply_to_position'
  devise_for :candidates
  devise_for :interviewers
  get "my_candidatures", to: 'pages#my_candidatures'
  get "dashboard", to: 'pages#dashboard'
  get "list_candidates", to: 'pages#list_candidates'

  resources :employees

  resources :positions do
      member do
        get :find_match
      end
    resources :candidatures do

    end
  end
  # devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/position.rb
class Position < ApplicationRecord
  validates :title, presence: true

  belongs_to :interviewer
  has_many :candidatures
  validate :must_have_one_skill

  # answered by @Taryn East - the second answer
  def must_have_one_skill
    errors.add(:base, 'You must select at least one skill') if self.array_skills.all?{|skill| skill.blank? }
  end

end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  skip_before_action :authenticate_candidate!
  skip_before_action :authenticate_interviewer!

  before_action :set_position, only: [:show, :edit, :update, :destroy, :find_match, :add_review]


  def index
    @positions = Position.all
  end

  def show
    @interviewers = Interviewer.all
    @position_skills = @position.array_skills
    @matching_expertises_array = []
    @matching_expertises = {}

    @interviewers.each do |interviewer|
      @matching_expertises_array =  interviewer.expertises & @position.array_skills
      @matching_expertises.store(interviewer, @matching_expertises_array)
    end
      @final_expertises_score = Hash[@matching_expertises.sort_by { |k, v| v.length }.reverse!]

    @employees = Employee.all
    @employee_skills = @position.array_skills
    @employee_matching_expertises_array = []
    @employee_matching_expertises = {}

    @employees.each do |employee|
    @employee_matching_expertises_array =  employee.expertises_array & @position.array_skills
    @employee_matching_expertises.store(employee, @employee_matching_expertises_array)
    end
      @employee_final_expertises_score = Hash[@employee_matching_expertises.sort_by { |k, v| v.length }.reverse!]

  end

  def new
    @position = Position.new
  end

  def create
    @position = current_interviewer.positions.new(position_params)

    @position.skills = ""
    @position.array_skills.each do |skill|
      @position.skills = @position.skills + skill + ", "
    end
    @position.skills = @position.skills.chop.chop

    if @position.save
      redirect_to position_path(@position)
      flash[:success] = "You created a new position/opening"

    else
      render :new
    end


  end

  def edit
  end

  def update
    if @position.update(position_params)
      redirect_to position_path(@position)
    else
      render :edit
    end
  end


  def destroy
    if @position.delete
      redirect_to positions_path

    else
      redirect_to position_path(@position)
    end
  end

  def find_match
    @matching_score = {}
    @candidates = Candidate.all
    @matching_skills_array = []
    @candidates.each do |candidate|
      @matching_skills_array = candidate.skill & @position.array_skills
      @matching_score.store(candidate, @matching_skills_array)
    end

    @final_matching_score = Hash[@matching_score.sort_by { |k, v| v.length }.reverse!]


  end

  private

  def set_position
    @position = Position.find(params[:id])
  end

  def position_params
    params.require(:position).permit(:title, :interviewer, array_skills:[])
  end

end

app/views/positions/_form.html.erb
<div class="container">
  <div class="row">
    <div class="mt-5 offset-2 col-md-8">
      <h3>Add/Modify a opening</h3>
    </div>
    <div class="mt-3 offset-2 col-md-8">
      <%= simple_form_for [@interviewer, @position] do |f| %>
        <%= f.input :title, required:true %>

       <%= f.input :array_skills, as: :check_boxes, label: 'Select the skills for the position (at least one)*', collection:[
        ['Python', "python"],
        ['Java', "java"],
        ['JavaScript', "javascript"],
        ['Ruby', "ruby"],
        ['C++', "c++"],
        ['Node.js', "node"],
        ['React', "react"],
        ['Django', "django"],
        ['Rails', "rails"],
        ['SQL', "sql"],
        ['Doker', "doker"],
        ['AWS', "aws"],
        ['Vue.js', "vue"],
        ['Marketing', "Marketing"],
        ['HR', "hr"],
        ['Finance', "finance"],
        ['IT', "it"],
        ], input_html: { multiple: true }, include_hidden: false %>

        <%= f.submit "Submit position", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/positions/edit.html.erb
<%= render 'form', position: @position %>

app/views/positions/find_match.html.erb
<div class="mt-4 container text-center">
<h2>FIND A MATCH FOR:</h2>
 <h2> <%= link_to @position.title, position_path(@position) %> </h2>
 <h3> Skills needed: <%= @position.array_skills.join(" ") %></h3>
</div>


<% if current_interviewer.candidatures.count() > 0 %>
<%my_count = 1%>
<div class="container text-right">
  <%= link_to "Create a position", new_position_path, class: "mt-3 btn btn-success" %>
</div>

<% my_count = 1%>
<table class="mt-4 table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Lastname</th>
      <th scope="col">Email</th>
      <th scope="col">Matching skills</th>
      <th scope="col">Skills fit</th>

      <th scope="col">Contact</th>

    </tr>
  </thead>
  <tbody>
<% @final_matching_score.each do |my_dict|%>
    <tr>
      <th scope="row"><%=my_count%></th>
      <td><%=   my_dict[0].lastname  %></td>
      <td><a href="mailto:"><%= my_dict[0].email %></a></td>
      <td><%= my_dict[1].join(" ") %></td>

      <% if (my_dict[1].length.to_f/@position.array_skills.length.to_f) > 0.70 %>
        <td style="color: green"> <%= my_dict[1].length %> / <%=@position.array_skills.length%></td>
      <% elsif (my_dict[1].length.to_f/@position.array_skills.length.to_f < 0.30) %>
        <td style="color: red"> <%= my_dict[1].length %> / <%=@position.array_skills.length%></td>
      <% else %>
        <td style="color: orange" > <%= my_dict[1].length %> / <%=@position.array_skills.length%></td>

      <% end %>




      <td><%= link_to "Appointment", "#", :class => "mt-2 mb-2 btn btn-primary btn-block"%></td>
    </tr>
 <% my_count += 1%>
<% end %>

  </tbody>
</table>



<% else %>
<div class="mt-4 container text-center">
<div class="mt-4 jumbotron">
  <h1 class="display-4">There are no candidatures yet</h1>


      <%= link_to "Explore candidates", list_candidates_path, class: "mt-4 btn btn-primary"%>
      <%= link_to "Find a match", positions_path, class: "mt-4 btn btn-primary"%>

    </div></div>
</div>
</div>
      <% end %>

app/views/positions/index.html.erb
<% if current_interviewer %>

<div class="mt-4 container text-center">
<h2>ALL CREATED POSITIONS IN THE DATABASE</h2>
</div>
<div class="container text-right">
  <%= link_to "Create a position", new_position_path, class: "mt-3 btn btn-success" %>
</div>
<% @positions.each do |position| %>
  <div class="container">
    <div class="mt-3 card mb-12">
      <div class="row no-gutters">
        <div class="col-md-1" style="background-color: #2382e8">
        </div>
        <div class="col-md-9">
          <div class="card-body">
          <h5><%= link_to position.title, position_path(position.id)%></h5>

              <p class="card-text">Skills: <%= position.skills %></p>
              <p class="card-text">Number of applicants: <%= position.candidatures.count %>  </p>
            <p class="card-text"><small class="text-muted">Create by employer: <%= position.interviewer.email %></small></p>


     <b>  <p class="card-text text-center">THE BEST EMPLOYEES TO MATCH ARE</p></b>
<table class="mt-2 table table-sm">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
      <th scope="col">Job</th>
      <th scope="col">Expertises</th>
      <th scope="col">Affinity</th>
      <th scope="col">Match</th>

    </tr>

  </thead>
  <tbody>

    <% employees = Employee.all %>
    <% position_skills = position.array_skills %>
    <% matching_expertises_array = []%>
    <% matching_expertises = {}%>
    <% employees.each do |employee| %>
      <% matching_expertises_array =  employee.expertises_array & position.array_skills %>
      <% matching_expertises.store(employee, matching_expertises_array) %>
    <% end%>
      <% employee_final_expertises_score = Hash[matching_expertises.sort_by { |k, v| v.length }.reverse!] %>


    <% my_count_interview = 1 %>

    <% employee_final_expertises_score.each do |my_dict|%>
    <tr>
      <th  scope="row"><%=my_count_interview%></th>
      <td><%= my_dict[0].email%></td>
      <td><%= my_dict[0].position%></td>

      <td><%= my_dict[0].expertises_array.join(" ")%></td>
      <% if  my_dict[1].length.to_f/position.array_skills.length.to_f > 0.5 %>
              <td style="color:green"><%= my_dict[1].join(" ")%></td>
      <% elsif my_dict[1].length.to_f/position.array_skills.length.to_f < 0.2 %>
              <td style="color:red"><%= my_dict[1].join(" ")%></td>
      <% else %>
            <td style="color:orange"><%= my_dict[1].join(" ")%></td>
      <% end %>
            <td><%= link_to "Match", position_candidatures_path(position), class:"btn btn-primary"%></td>

    </tr>
        <% my_count_interview += 1 %>
    <% end %>
  </tbody>
</table>



    <b>  <p class="card-text text-center">THE BEST HR FOR THIS POSITION ARE</p></b>
<table class="mt-2 table table-sm">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
      <th scope="col">Expertises</th>
      <th scope="col">Matching</th>
    </tr>

  </thead>
  <tbody>

    <% interviewers = Interviewer.all %>
    <% position_skills = position.array_skills %>
    <% matching_expertises_array = []%>
    <% matching_expertises = {}%>
    <% interviewers.each do |interviewer| %>
      <% matching_expertises_array =  interviewer.expertises & position.array_skills %>
      <% matching_expertises.store(interviewer, matching_expertises_array) %>
    <% end%>
      <% final_expertises_score = Hash[matching_expertises.sort_by { |k, v| v.length }.reverse!] %>


    <% my_count_interview = 1 %>

    <% final_expertises_score.each do |my_dict|%>
    <tr>
      <th  scope="row"><%=my_count_interview%></th>
      <td><%= my_dict[0].email%></td>
      <td><%= my_dict[0].expertises.join(" ")%></td>
      <% if  my_dict[1].length.to_f/position.array_skills.length.to_f > 0.5 %>
              <td style="color:green"><%= my_dict[1].join(" ")%></td>
      <% elsif my_dict[1].length.to_f/position.array_skills.length.to_f < 0.2 %>
              <td style="color:red"><%= my_dict[1].join(" ")%></td>
      <% else %>
            <td style="color:orange"><%= my_dict[1].join(" ")%></td>
      <% end %>

    </tr>
        <% my_count_interview += 1 %>
    <% end %>
  </tbody>
</table>


          </div>
        </div>
        <div class="mt-2 col-md-2">
          <%= link_to "See position", position_path(position.id), :class => "mt-2 mb-2 btn btn-primary btn-block"%>
          <%= link_to "See candidatures", position_candidatures_path(position), :class => "mt-2 mb-2 btn btn-warning btn-block"%>
          <%= link_to "Find match", find_match_position_path(position.id), :class => "mt-2 mb-2 btn btn-primary btn-block"%>
          <%= link_to "Edit position", edit_position_path(position.id), :class => "mt-2 mb-2 btn btn-light btn-block"%>

          <%= link_to "Delete this position", position_path(position), method: :delete, :class => "mt-2 mb-2 btn btn-light btn-block",data: { confirm: "Are you sure you want to delete this position?" } %>
        </div>
      </div>
    </div>
  </div>
<% end %>


<% else %>
<div class="mt-4 container text-center">
  <h1>ALL OPEN POSITIONS</h1>
</div>



<% @positions.each do |position| %>
  <div class="container">
    <div class="mt-3 card mb-12">
      <div class="row no-gutters">
        <% if position.candidatures.include?(current_candidate.id.to_s) %>

        <div class="col-md-2" style="background-color: #0fdb3c">
        </div>
        <% else %>
        <div class="col-md-2 text-center" style="background-color: #f2242f">
        </div>
        <% end %>
        <div class="col-md-7">
          <div class="card-body">
          <h5><%= link_to position.title, position_path(position.id)%></h5>
            <p class="mt-3 card-text">Skills required: <%= position.skills %></p>
            <% current_candidate_skill_string = "" %>
            <% current_candidate.skill.each do |skill| %>
              <% current_candidate_skill_string = current_candidate_skill_string + skill + ", " %>
            <% end %>
            <% current_candidate_skill_string.chop!.chop! %>
            <p class="card-text">Your skills: <%= current_candidate.skill.join(" ") %></p>


          <% matching_skills_array = [] %>
          <% candidate_skills_array = current_candidate.skill %>
          <% position_skills_array = position.array_skills %>

          <% matching_skills_array = candidate_skills_array & position_skills_array %>

          <% matching_skills_string = "" %>
          <% matching_skills_array.each do |skill| %>
            <% matching_skills_string = matching_skills_string + skill + ", " %>
          <% end %>
          <%matching_skills_string = matching_skills_string.chop.chop%>





      <p class="card-text">Matching skills: <%= matching_skills_array.join(" ") %></p>

        <% if  (matching_skills_array.length.to_f / position.array_skills.length.to_f).to_f*100 > 70 %>

        <p class="card-text" style="color:green">Percentage matching: <%= (matching_skills_array.length / position.array_skills.length).to_i*100 %>%</p>

        <% elsif  (matching_skills_array.length.to_f / position.array_skills.length.to_f).to_f*100 < 30 %>
          <p class="card-text" style="color:red">Percentage matching: <%= (matching_skills_array.length.to_f / position.array_skills.length.to_f).to_i*100 %>%</p>
        <% else %>
            <p class="card-text" style="color:orange">Percentage matching: <%= (matching_skills_array.length.to_f / position.array_skills.length.to_f).to_f*100 %>%</p>
        <% end %>



      <p class="card-text"><small class="text-muted">Number of applicants: <%=position.candidatures.count() %> </small></p>
    </div>
  </div>
  <div class="mt-2 col-md-3">

<% id_candiatures_for_position = [] %>
<% position.candidatures.each do |c| %>
<% id_candiatures_for_position << c.id %>
<% end %>

          <% if id_candiatures_for_position.include?(current_candidate.id) %>
            <small style="color: green;" class="ml-2">Applied</small>
            <%= link_to "Delete application", "#", :class => "mt-2 mb-2 btn btn-primary btn-block"%>
          <% else %>
            <small style="color: red;" class="ml-2">Not applied</small>
            <%= link_to "Apply", new_position_candidature_path(position), :class => "mt-2 mb-2 btn btn-primary btn-block"%>
          <% end %>
        <%= link_to "See more detail", position_path(position.id), :class => "mt-2 mb-2 btn btn-light btn-block"%>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% end %>

app/views/positions/new.html.erb
<%= render 'form', position: @position %>

app/views/positions/show.html.erb
<% if current_interviewer %>
  <div class="container">
    <h3 class="mt-4">You are visulalizing the details for the position: <%= @position.title %> </h3>

    <div class="mt-3 card mb-12">
      <div class="row no-gutters">
        <div class="col-md-1" style="background-color: #42f5b3">
        </div>
        <div class="col-md-9">
          <div class="card-body">
            <h5 class="card-title"><h5><%= link_to @position.title, position_path(@position)%></h5>
</h5>
            <p class="card-text">Skills: <%= @position.skills %></p>
            <p class="card-text">Number of applicants: <%=@position.candidatures.length%></p>

            <b>  <p class="card-text text-center">THE BEST EMPLOYEE FOR THIS POSITION ARE</p></b>
<table class="mt-2 table table-sm">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
      <th scope="col">Expertises</th>
      <th scope="col">Matching</th>
    </tr>

  </thead>
  <tbody>
    <% my_count = 1 %>
                  <% @employee_final_expertises_score.each do |my_dict|%>
    <tr>
      <th  scope="row"><%=my_count%></th>
      <td><%= my_dict[0].email%></td>
      <td><%= my_dict[0].expertises_array.join(" ")%></td>
      <% if  my_dict[1].length.to_f/@position.array_skills.length.to_f > 0.5 %>
              <td style="color:green"><%= my_dict[1].join(" ")%></td>
      <% elsif my_dict[1].length.to_f/@position.array_skills.length.to_f < 0.2 %>
              <td style="color:red"><%= my_dict[1].join(" ")%></td>
      <% else %>
            <td style="color:orange"><%= my_dict[1].join(" ")%></td>
      <% end %>

    </tr>
        <% my_count += 1 %>
    <% end %>
  </tbody>
</table>







            <b>  <p class="card-text text-center">THE BEST HR FOR THIS POSITION ARE</p></b>
<table class="mt-2 table table-sm">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
      <th scope="col">Expertises</th>
      <th scope="col">Matching</th>
    </tr>

  </thead>
  <tbody>
    <% my_count_interview = 1 %>
                  <% @final_expertises_score.each do |my_dict|%>
    <tr>
      <th  scope="row"><%=my_count_interview%></th>
      <td><%= my_dict[0].email%></td>
      <td><%= my_dict[0].expertises.join(" ")%></td>
      <% if  my_dict[1].length.to_f/@position.array_skills.length.to_f > 0.5 %>
              <td style="color:green"><%= my_dict[1].join(" ")%></td>
      <% elsif my_dict[1].length.to_f/@position.array_skills.length.to_f < 0.2 %>
              <td style="color:red"><%= my_dict[1].join(" ")%></td>
      <% else %>
            <td style="color:orange"><%= my_dict[1].join(" ")%></td>
      <% end %>

    </tr>
        <% my_count_interview += 1 %>
    <% end %>
  </tbody>
</table>




            <p class="card-text"><small class="text-muted">Create by employer: <%= @position.interviewer.email %></small></p>
          </div>
        </div>
        <div class="mt-2 col-md-2">
                        <% if @position.candidatures.length == 0 %>

            <p class="card-text" style="color:red"><small>No candidatures yet</small></p>
          <% else %>

            <p class="card-text" style="color:green"><small>See candidates in the table </small></p>

          <% end %>
          <%= link_to "Find match", find_match_position_path(@position), :class => "mt-2 mb-2 btn btn-primary btn-block"%>

          <%= link_to "Edit position", edit_position_path(@position.id), :class => "mt-2 mb-2 btn btn-light btn-block"%>
          <%= link_to "Delete this position", position_path(@position), method: :delete, :class => "mt-2 mb-2 btn btn-light btn-block",data: { confirm: "Are you sure you want to delete this position?" } %>
        </div>
      </div>

              <% if @position.candidatures.count() > 0 %>

<%my_count = 1%>

<table class="mt-4 table">
    <b><caption class="ml-2 " style="caption-side: top; color:black; font-weight: bold;" >THE CANDIDATES FOR THIS POSITION:</caption></b>

  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Lastname</th>
      <th scope="col">Email</th>
      <th scope="col">Matching skills</th>
      <th scope="col">Contact</th>
      <th scope="col">Application date</th>

    </tr>
  </thead>
  <tbody>
    <% @position.candidatures.each do |candidature|%>

          <% matching_skills_array = [] %>
          <% candidate_skills_array = candidature.candidate.skill %>
          <% position_skills_array = candidature.position.array_skills %>
          <% matching_skills_array = candidate_skills_array & position_skills_array %>
          <% matching_skills_string = "" %>
          <% matching_skills_array.each do |skill| %>
            <% matching_skills_string = matching_skills_string + skill + ", " %>

          <% end %>
          <%matching_skills_string = matching_skills_string.chop.chop%>


    <tr>
      <th scope="row"><%= my_count %></th>
      <td><%= candidature.candidate.lastname %></td>
      <td><a href="mailto:<%= candidature.candidate.email %>"><%= candidature.candidate.email %></a></td>
      <td><%= matching_skills_array.join(" ")%></td>
      <td> <%= candidature.candidate.email %></td>
      <td> <%= candidature.created_at %></td>


    </tr>
    <%my_count += 1%>

      <% end %>

    <tr>
  </tbody>
</table>



  <% end %>


    </div>

  </div>



<% else %>

  <div class="mt-4 container">
    <h2 class="text-center">POSITION DETAILS</h2>
    <div class="mt-3 card mb-12">

      <div class="row no-gutters">
        <div class="col-md-2" style="background-color: #42f5b3">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><%= @position.title %></h5>
            <p class="card-text">Skill required: <%= @position.skills %></p>
            <% current_candidate_skill_string = "" %>
            <% current_candidate.skill.each do |skill| %>
              <% current_candidate_skill_string = current_candidate_skill_string + skill + ", " %>
            <% end %>
            <% current_candidate_skill_string.chop!.chop! %>
            <p class="card-text">Your skills: <%= current_candidate_skill_string %></p>

          <% matching_skills_array = [] %>
          <% candidate_skills_array = current_candidate.skill %>
          <% position_skills_array = @position.array_skills %>
          <% matching_skills_array = candidate_skills_array & position_skills_array %>
          <% matching_skills_string = "" %>
          <% matching_skills_array.each do |skill| %>
            <% matching_skills_string = matching_skills_string + skill + ", " %>
          <% end %>
          <%matching_skills_string = matching_skills_string.chop.chop%>



            <p class="card-text">Matching skills: <%= matching_skills_array.join(" ") %> <%= matching_skills_array.length %> / <%= @position.array_skills.length %></p>
            <p class="card-text">Number of applicants: <%=@position.candidatures.length%></p>

          </div>
        </div>
        <div class="mt-2 col-md-2">
          <% if @position.candidatures.include?(current_candidate.id.to_s) %>
            <%= link_to "Delete application", delete_application_position_path, :class => "mt-2 mb-2 btn btn-primary btn-block"%>
            <% else %>
            <%= link_to "Apply", new_position_candidature_path(@position), :class => "mt-2 mb-2 btn btn-primary btn-block"%>
            <%= link_to "Go back", positions_path, :class => "mt-2 mb-2 btn btn-light btn-block"%>

          <% end %>
        </div>
      </div>
    </div>
  </div>

<% end %>