config/routes.rb
Rails.application.routes.draw do
  get 'candidatures/apply_to_position'
  devise_for :candidates
  devise_for :interviewers
  get "my_candidatures", to: 'pages#my_candidatures'
  get "dashboard", to: 'pages#dashboard'
  get "list_candidates", to: 'pages#list_candidates'

  resources :employees

  resources :positions do
      member do
        get :find_match
      end
    resources :candidatures do

    end
  end
  # devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/candidature.rb
class Candidature < ApplicationRecord
  belongs_to :candidate
  belongs_to :interviewer
  belongs_to :position
end

app/controllers/candidatures_controller.rb
class CandidaturesController < ApplicationController
  skip_before_action :authenticate_candidate!
  skip_before_action :authenticate_interviewer!

  before_action :set_candidature, only: [:show, :edit, :update, :destroy, :add_review]


def edit
  @position = Position.find(params[:position_id])
  @candidature = Candidature.find(params[:id])
end

def update
  @position = Position.find(params[:position_id])
  @candidature = Candidature.find(params[:id])
  if @candidature.update(candidature_params)
        redirect_to position_candidatures_path(@position)
    else
      render :edit
    end
end

  def index
    @employees = Employee.all
    @candidatures = Candidature.all
    @position = Position.find(params[:position_id])

    @employee_matching_expertises_array = []
    @employee_matching_expertises = {}

    @employees.each do |employee|
    @employee_matching_expertises_array =  employee.expertises_array & @position.array_skills
    @employee_matching_expertises.store(employee, @employee_matching_expertises_array)
    end
      @employee_final_expertises_score = Hash[@employee_matching_expertises.sort_by { |k, v| v.length }.reverse!]


  end

  def show
  end

  def new
    @position = Position.find(params[:position_id])
    @candidature = Candidature.new

    @matching_skills_array = []

    candidate_skills_array = current_candidate.skill
    position_skills_array = @position.array_skills

    @matching_skills_array = candidate_skills_array & position_skills_array


    @matching_skills_string = ""
    @matching_skills_array.each do |skill|
      @matching_skills_string = @matching_skills_string + skill + ", "
    end
    @matching_skills_string = @matching_skills_string.chop.chop

  end


  def create
    @position = Position.find(params[:position_id])
    @candidature = Candidature.new
    @candidature.candidate = current_candidate
    @candidature.position = @position
    @candidature.interviewer = @position.interviewer
    if @candidature.save
      redirect_to my_candidatures_path
      flash[:success] = "You applied"
    else
      redirect_to position_path(@position)
      flash[:alert] = "Something went wrong, try again"
    end
  end

  def destroy
    if @candidature.delete
      redirect_to my_candidatures_path

    else
      redirect_to position_candidature_path(@candidature)
    end
  end


  private

  def set_candidature
    @position = Position.find(params[:position_id])
  end

  def candidature_params
    params.require(:candidature).permit(:position, :review)
  end



end

app/views/candidatures/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mt-5 offset-2 col-md-8">

<%= simple_form_for [@position, @candidature] do |f| %>
  <%= f.input :review, as: :text, input_html: {rows: 15, cols: 10} %>
<%= button_tag(type: 'submit', class: "btn btn-primary") do %> Add review <% end %>
<%= link_to "Go back", position_candidatures_path%>
<% end %>

</div>
</div>
</div>

app/views/candidatures/index.html.erb
<% if current_interviewer %>

<div class="mt-4 container text-center">
<h2>ALL CANDIDATURES FOR THE POSITION:</h2>
<h3><%= @position.title %></h3>
</div>
<div class="container text-right">
  <%= link_to "Create a position", new_position_path, class: "mt-3 btn btn-success" %>
</div>

<% my_count = 1 %>




      <% @candidatures.each do |candidature| %>
<% if candidature.position = @position %>
<table class="mt-4 table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Firstname</th>
      <th scope="col">Lastname</th>
      <th scope="col">Email</th>
      <th scope="col">Review</th>

    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= my_count %></th>
      <td><%= candidature.candidate.firstname %></td>
      <td><%= candidature.candidate.lastname %></td>
      <td><%= candidature.candidate.email %></td>
<% if candidature.review  %>
        <td><%= link_to "See review", edit_position_candidature_path(@position, candidature) %></td>

  <% else %>
        <td><%= link_to "Add review", edit_position_candidature_path(@position, candidature) %></td>

<% end %>

    </tr>
  </tbody>
</table>

<% my_count = my_count+1%>

  <h5 class="ml-2 text">THE BEST EMPLOYEES TO MATCH WITH THE CANDIDATE ARE:</h5>
<table class="ml-2 mt-2 table-info table-sm table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
      <th scope="col">Expertises</th>
      <th scope="col">Matching</th>
      <th scope="col">Send an email to both</th>

    </tr>

  </thead>
  <tbody>
    <% my_count = 1 %>
                  <% @employee_final_expertises_score.each do |my_dict|%>
    <tr>
      <th  scope="row"><%=my_count%></th>
      <td><%= my_dict[0].email%></td>
      <td><%= my_dict[0].expertises_array.join(" ")%></td>
      <% if  my_dict[1].length.to_f/@position.array_skills.length.to_f > 0.5 %>
              <td style="color:green"><%= my_dict[1].join(" ")%></td>
      <% elsif my_dict[1].length.to_f/@position.array_skills.length.to_f < 0.2 %>
              <td style="color:red"><%= my_dict[1].join(" ")%></td>
      <% else %>
            <td style="color:orange"><%= my_dict[1].join(" ")%></td>
      <% end %>
<td><%= mail_to my_dict[0].email+";"+candidature.candidate.email,"Match", subject:"Match with RecruitT", body: " You matched with RecruiT for the position " +@position.title + ". Your point of contact is eht employee: " + my_dict[0].firstname%>

</td>
    </tr>
        <% my_count += 1 %>
    <% end %>
  </tbody>
</table>


<% end %>




  <!-- <div class="container">
    <div class="mt-3 card mb-12">
      <div class="row no-gutters">
        <div class="col-md-2" style="background-color: #2382e8">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><%= candidature.position.title %></h5>
              <p class="card-text">Skills: <%= candidature.position.skills %></p>
              <p class="card-text">Applicant: <%= candidature.candidate.firstname %> </p>
            <p class="card-text"><small class="text-muted">Create by employer: <%= candidature.position.interviewer.email %></small></p>
          </div>
        </div>
        <div class="mt-2 col-md-2">
          <%= link_to "See position", position_path(@position.id), :class => "mt-2 mb-2 btn btn-primary btn-block"%>
          <%= link_to "Edit position", edit_position_path(@position.id), :class => "mt-2 mb-2 btn btn-light btn-block"%>

          <%= link_to "Delete this position", position_path(@position), method: :delete, :class => "mt-2 mb-2 btn btn-light btn-block",data: { confirm: "Are you sure you want to delete this position?" } %>
        </div>
      </div>
    </div>
  </div> -->
<% end %>


<% else %>
<div class="mt-4 container text-center">
  <h1>SEE YOUR CANDIDATURES</h1>
</div>



<% @candidatures.each do |candidature| %>
  <div class="container">
    <div class="mt-3 card mb-12">
      <div class="row no-gutters">
        <% if candidature.candidate == current_candidate %>

        <div class="col-md-2" style="background-color: #0fdb3c">
        </div>
        <% else %>
        <div class="col-md-2 text-center" style="background-color: #f2242f">
        </div>
        <% end %>
        <div class="col-md-7">
          <div class="card-body">
            <h5 class="card-title"><%= candidature.position.title %></h5>
            <p class="card-text">Skills required: <%= candidature.position.skills %></p>
            <% current_candidate_skill_string = "" %>
            <% current_candidate.skill.each do |skill| %>
              <% current_candidate_skill_string = current_candidate_skill_string + skill + ", " %>
            <% end %>
            <% current_candidate_skill_string.chop!.chop! %>
            <p class="card-text">Your skills: <%= current_candidate_skill_array.join(" ") %></p>
            <p class="card-text"><small class="text-muted">Number of applicants: <%=@position.candidatures.count%> </small></p>
          </div>
        </div>
        <div class="mt-2 col-md-3">

          <% if candidature.candidate == current_candidate %>
            <small style="color: green;" class="ml-2">Applied</small>
            <%= link_to "Delete application", "#", :class => "mt-2 mb-2 btn btn-primary btn-block"%>
          <% else %>
            <small style="color: red;" class="ml-2">Not applied</small>
            <%= link_to "Apply", new_position_candidature_path(@position), :class => "mt-2 mb-2 btn btn-primary btn-block"%>
          <% end %>
        <%= link_to "See more detail", position_path(@position.id), :class => "mt-2 mb-2 btn btn-light btn-block"%>

        </div>
      </div>
    </div>
  </div>
<% end %>

<% end %>

app/views/candidatures/new.html.erb
      <% current_candidate_skill_string = "" %>
      <% current_candidate.skill.each do |skill| %>
      <% current_candidate_skill_string = current_candidate_skill_string + skill + ", " %>
      <% end %>
      <% current_candidate_skill_string.chop!.chop! %>


<div class="container">
<h2 class="mt-2 text-center">Application</h2>
<div class="mt-4 jumbotron">
  <h1 class="display-4"><%= @position.title %> </h1>

  <p class="mt-4 lead">Skill required: <%=@position.skills%></p>
  <hr class="my-4">
    <div col-md-6>
  <p class="lead">Your skills: <%= current_candidate.skill.join(" ") %></p>
  <hr class="my-4">
  </div>

  <p>Matching skills: <%= @matching_skills_string %></p>
<div id="my_candidature_form" class="text-center my_candidature_form mt-3 offset-2 col-md-8">
      <%= simple_form_for [@position, @candidature] do |f| %>

      <%= f.submit "Apply ", class: " btn btn-primary" %>
      <% end %>
      <%= link_to "Go back", positions_path, class: "mt-4 btn btn-light"%>
    </div></div>
</div>

app/views/candidatures/show.html.erb
fdsfs