config/routes.rb
Rails.application.routes.draw do
  get 'candidatures/apply_to_position'
  devise_for :candidates
  devise_for :interviewers
  get "my_candidatures", to: 'pages#my_candidatures'
  get "dashboard", to: 'pages#dashboard'
  get "list_candidates", to: 'pages#list_candidates'

  resources :employees

  resources :positions do
      member do
        get :find_match
      end
    resources :candidatures do

    end
  end
  # devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if candidate_signed_in? %>
            <li class="nav-item ">
          Welcome <%= current_candidate.firstname %>!
        </li>
        <li class="nav-item ">
          <%= link_to "All openings", positions_path, class: "nav-link" %>
        </li>
        <li class="nav-item ">
          <%= link_to "My candidatures", my_candidatures_path, class: "nav-link" %>
        </li>
<!--         <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li> -->
        <li class="nav-item dropdown">
          <%= image_tag "profile_candidate_logo.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
<!--             <%= link_to "Action", "#", class: "dropdown-item" %>-->

            <%= link_to "Edit profile/skills", edit_candidate_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_candidate_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% elsif interviewer_signed_in? %>
        <li class="nav-item ">
          <%= link_to "Create a position", new_position_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Open positions", positions_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
                        <li class="nav-item ">
          <%= link_to "Candidates", list_candidates_path, class: "nav-link" %>
        </li>
        <li class="nav-item ">
          <%= link_to "Employees", employees_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "profile_hr_logo.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
<!--             <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %> -->
            <%= link_to "Log out", destroy_interviewer_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Login as candidate", new_candidate_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
                  <%= link_to "Login as recruiter", new_interviewer_session_path, class: "nav-link" %>
        </li>

      <% end %>
    </ul>
  </div>
</div>