config/routes.rb
Rails.application.routes.draw do
  get 'candidatures/apply_to_position'
  devise_for :candidates
  devise_for :interviewers
  get "my_candidatures", to: 'pages#my_candidatures'
  get "dashboard", to: 'pages#dashboard'
  get "list_candidates", to: 'pages#list_candidates'

  resources :employees

  resources :positions do
      member do
        get :find_match
      end
    resources :candidatures do

    end
  end
  # devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/add_employee.html.erb
<div class="container">
  <div class="row">
    <div class="mt-5 offset-2 col-md-8">
      <h3>Add/Modify a opening</h3>
    </div>
    <div class="mt-3 offset-2 col-md-8">
      <%= simple_form_for [@interviewer] do |f| %>
        <%= f.input :title, required:true %>

       <%= f.input :array_skills, as: :check_boxes, label: 'Select the skills for the position (at least one)*', collection:[
        ['Python', "python"],
        ['Java', "java"],
        ['JavaScript', "javascript"],
        ['Ruby', "ruby"],
        ['C++', "c++"],
        ['Node.js', "node"],
        ['React', "react"],
        ['Django', "django"],
        ['Rails', "rails"],
        ['SQL', "sql"],
        ['Doker', "doker"],
        ['AWS', "aws"],
        ['Vue.js', "vue"],
        ['Marketing', "Marketing"],
        ['HR', "hr"],
        ['Finance', "finance"],
        ['IT', "it"],
        ], input_html: { multiple: true }, include_hidden: false %>

        <%= f.submit "Submit position", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="mt-4 container text-center">
<h2>DASHBOARD</h2>
</div>


<% if current_interviewer.candidatures.count() > 0 %>
<%my_count = 1%>
<div class="container text-right">
  <%= link_to "Create a position", new_position_path, class: "mt-3 btn btn-success" %>
</div>


<table class="mt-4 table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Position</th>
      <th scope="col">Lastname</th>
      <th scope="col">Email</th>
      <th scope="col">Matching skills</th>
      <th scope="col">Contact</th>

    </tr>
  </thead>
  <tbody>
<% current_interviewer.candidatures.each do |candidature| %>

          <% matching_skills_array = [] %>
          <% candidate_skills_array = candidature.candidate.skill %>
          <% position_skills_array = candidature.position.array_skills %>
          <% matching_skills_array = candidate_skills_array & position_skills_array %>
          <% matching_skills_string = "" %>
          <% matching_skills_array.each do |skill| %>
            <% matching_skills_string = matching_skills_string + skill + ", " %>

          <% end %>
          <%matching_skills_string = matching_skills_string.chop.chop%>
    <tr>
      <th scope="row"><%= my_count %></th>
      <td> <%= link_to candidature.position.title, position_path(candidature.position.id) %></td>
      <td><%= candidature.candidate.lastname %></td>
      <td><a href="mailto:<%= candidature.candidate.email %>"><%= candidature.candidate.email %></a></td>
      <td><%=matching_skills_array.join(" ")%></td>
      <td><%= link_to "Appointment", "#", :class => "mt-2 mb-2 btn btn-primary btn-block"%>
</td>


    </tr>
    <%my_count += 1%>

      <% end %>
  </tbody>
</table>



<% else %>

<div class="mt-4 container text-center">
<div class="mt-4 jumbotron">
  <h1 class="display-4">There are no candidatures yet</h1>


      <%= link_to "Explore candidates", list_candidates_path, class: "mt-4 btn btn-primary"%>
      <%= link_to "Find a match", positions_path, class: "mt-4 btn btn-primary"%>

    </div></div>
</div>
</div>
      <% end %>

app/views/pages/home.html.erb
<% if current_candidate %>

<div class="container">
  <div class="mt-5 text-center">
    <h1>Welcome to RecruitT <%= current_candidate.firstname%></h1>
    <h5>RecruitT is the best platform to apply to exiting coding jobs and find easily a positon that matches your skills </h5>
  </div>
  <div class="row">
  </div>
      <div class="mt-5 row justify-content-center">
          <%= link_to "All openings", positions_path, class: "btn btn-primary" %>
    </div>
    <div class="mt-5 row justify-content-center">
      <%= image_tag "logo.png" %>
    </div>

    </div>
</div>


<% elsif current_interviewer %>

<div class="container">
  <div class="mt-5 text-center">
    <h1>Welcome to RecruitT <%= current_interviewer.email%></h1>
    <h5>RecruitT is the best platform to apply to exiting coding jobs and find easily a positon that matches your skills </h5>
  </div>
  <div class="row">
  </div>
      <div class="mt-5 row justify-content-center">
          <%= link_to "All openings", positions_path, class: "btn btn-primary" %>
    </div>
    <div class="mt-5 row justify-content-center">
      <%= image_tag "logo.png" %>
    </div>

    </div>
</div>


<% else %>
<div class="container">
  <div class="mt-5 text-center">
    <h1>Welcome to RecruitT</h1>
    <h5>RecruitT is the best platform to apply to exiting coding jobs and find easily a positon that matches your skills </h5>
  </div>
  <div class="row">
    <div class="mt-5 col-md-6">
      <div class="text-center">
        <h2>For Recruiters</h2>
          <div class="row ">
            <div class="offset-2">
              <%= link_to "Signup as recuriter", new_interviewer_registration_path, class: "btn btn-primary" %>
              <%= link_to "Login as retruiter", new_interviewer_session_path, class: "btn btn-primary" %>
            </div>
          </div>
      </div>
    </div>
    <div class="mt-5 col-md-6">
      <div class="text-center">
        <h2>For Candidates</h2>
        <div class="row">
            <div class="offset-2">
              <%= link_to "Signup as candidate", new_candidate_registration_path, class: "btn btn-primary" %>
              <%= link_to "Login as candiadte", new_candidate_session_path, class: "btn btn-primary" %>
            </div>
          </div>
      </div>
    </div>
  </div>
      <div class="mt-5 row justify-content-center">
      <div class="">
      <%= image_tag "logo.png" %>
    </div>

    </div>
</div>


<% end %>

app/views/pages/list_candidates.html.erb
<div class="mt-4 container text-center">
<h2>ALL CANDIDATES</h2>
</div>
<% if Candidate.all.count >0   %>
<div class="container text-right">
  <%= link_to "Find fit for a position", positions_path, class: "mt-3 btn btn-success" %>
</div>

<% Candidate.all.each do |candidate| %>
  <div class="container">
    <div class="mt-3 card mb-12">
      <div class="row no-gutters">
        <div class="col-md-2" style="background-color: #b443fa">
        </div>
        <div class="col-md-8">
          <div class="card-body">
          <h5><%=candidate.firstname%> <%=candidate.lastname%></h5>
              <p class="card-text">Skills: <%= candidate.skill.join(" ") %></p>
              <p class="card-text">Number of applications done: <%= candidate.candidatures.count %>  </p>
            <p class="card-text"><small class="text-muted">Create at: <%= candidate.created_at %></small></p>
          </div>
        </div>
        <div class="mt-2 col-md-2">
          <%= link_to "Find fit", positions_path, :class => "mt-2 mb-2 btn btn-primary btn-block"%>
        </div>
      </div>
    </div>
  </div>


  <% end %>
  <% else %>

<div class="mt-4 container text-center">
<div class="mt-4 jumbotron">
  <h1 class="display-4">There are no candidatures yet</h1>


      <%= link_to "Explore candidates", list_candidates_path, class: "mt-4 btn btn-primary"%>
      <%= link_to "Find a match", positions_path, class: "mt-4 btn btn-primary"%>

    </div></div>
</div>
</div>
<% end %>

app/views/pages/my_candidatures.html.erb
<div class="mt-4 container text-center">
<h2>ALL MY CANDIDATURES</h2>
</div>
<% if current_candidate.candidatures.count > 0 %>

<% current_candidate.candidatures.each do |candidature| %>
  <div class="container">
    <div class="mt-3 card mb-12">
      <div class="row no-gutters">
        <div class="col-md-2" style="background-color: #2382e8">
        </div>
        <div class="col-md-8">
          <div class="card-body">
          <h5><%= link_to candidature.position.title, position_path(candidature.position.id)%></h5>
            <h8 class="card-title">Required skills: <%= candidature.position.skills %></h8>
            <p class="card-text">Number of applicants: <%= candidature.position.candidatures.count %>  </p>

          </div>
        </div>
        <div class="mt-2 col-md-2">
          <%= link_to "See position", position_path(candidature.position.id), :class => "mt-2 mb-2 btn btn-primary btn-block"%>
          <%= link_to "Delete", position_candidature_path(candidature.position, candidature), method: :delete, :class => "mt-2 mb-2 btn btn-light btn-block",data: { confirm: "Are you sure you want to delete this candidature?" } %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% else %>
  <div class="mt-4 container">
    <p class="text-center" style="color:red">You have not applied yet to any job openings</p>
    <%= link_to "See open positions", positions_path, :class => "mt-2 mb-2 btn btn-primary btn-block"%>
</div>


<% end %>

<div class="container">
</div>